version: "3.8"
services:
  webserver:
    env_file: ./webserver/.dev.env
    command: go run ./src/.
    volumes:
      - ./webserver/src:/app/src/.
    ports:
      - 3000:8080
  db:
    env_file: ./webserver/.dev.env
  worker:
    env_file: ./worker/.dev.env
    command: go run ./src/.
    volumes:
      - ./worker/src:/app/src/.
    ports:
      - 4000:8080
