version: "3.8"
services:
  webserver:
    container_name: webserver
    build:
      context: ./webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 50s
      timeout: 50s
      retries: 1

  db:
    container_name: webserver-db
    image: mongo:7.0

  worker:
    container_name: worker
    build:
      context: ./worker
    depends_on:
      webserver:
        condition: service_healthy
        restart: true
