version: '3.8'
services:
  webserver:
    env_file: ./webserver/.dev.env
    entrypoint: bash
    tty: true
    volumes:
      - ./webserver/src:/app/src/.
    ports:
      - 3000:8080
  worker:
    env_file: ./worker/.dev.env
    entrypoint: bash
    tty: true
    volumes:
      - ./worker/src:/app/src/.
    ports:
      - 4000:8080